/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainWindow.java
 *
 * Created on May 1, 2010, 3:35:08 PM
 */

package JIstanbulDesktop;

import iett.Connector;
import iett.Line;
import iett.Time;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emre
 */
public class MainWindow extends javax.swing.JFrame {

    private Connector conn;
    DefaultTableModel tableModel;

    /** Creates new form MainWindow */
    public MainWindow() {
        initComponents();
        initLibrary();
    }

    private void initLibrary(){
        conn = new Connector();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lineCode = new javax.swing.JTextField();
        fetchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        timetable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hat Kodu:");

        lineCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineCodeActionPerformed(evt);
            }
        });

        fetchButton.setText("Saat Bul");
        fetchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchButtonActionPerformed(evt);
            }
        });

        timetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "A-H.İçi", "B-H.İçi", "A-Cumartesi", "B-Cumartesi", "A-Pazar", "B-Pazar"
            }
        ));
        jScrollPane1.setViewportView(timetable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lineCode, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fetchButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lineCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fetchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lineCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lineCodeActionPerformed

    private void fetchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchButtonActionPerformed
        try {
            Line line = conn.downloadLine(lineCode.getText());
            ArrayList<ArrayList<Time>> times = line.getTimetable();
            String from = line.getFrom();
            String to = line.getTo();


            tableModel = new DefaultTableModel();
            tableModel.addColumn("A - H.içi", times.get(0).toArray());
            tableModel.addColumn("B - H.içi", times.get(1).toArray());
            tableModel.addColumn("A - Cumartesi", times.get(2).toArray());
            tableModel.addColumn("B - Cumartesi", times.get(3).toArray());
            tableModel.addColumn("A - Pazar", times.get(4).toArray());
            tableModel.addColumn("B - Pazar", times.get(5).toArray());

            //ArrayList<Time[]> rows = line.getRowBasedTimeTable();
            //System.out.println("Inserting"+ rows.get(0));
            //tableModel.insertRow(tableModel.getRowCount(), rows.get(0));

            timetable.setModel(tableModel);
        }
        catch (Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_fetchButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fetchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lineCode;
    private javax.swing.JTable timetable;
    // End of variables declaration//GEN-END:variables

}
